name: Downgraded Release

on:
    push:
        tags:
            - '*'

jobs:
    downgrade_release:
        runs-on: ubuntu-latest

        steps:
            -   uses: "actions/checkout@v2"

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            # downgrade /src and /vendor to PHP 8.0
            -   run: vendor/bin/rector process src vendor --config build-downgrade/rector-downgrade-php-80.php --ansi
            -   run: vendor/bin/ecs check src --fix --ansi

            # copy PHP 7.2 composer
            -   run: cp build-downgrade/composer-php-80.json composer.json

            # clear the dev files
            -   run: rm -rf build build-downgrade .github tests tools schema

            # setup git user
            -
                run: |
                    git config user.email "action@github.com"
                    git config user.name "GitHub Action"

            # publish to the same repository with a new tag
            -
                name: "Tag Downgraded Code"
                run: |
                    # separate a "git add" to add untracked (new) files too
                    git add --all
                    git commit -m "release PHP 8.0 downgraded"

                    # force push tag, so there is only 1 version
                    git tag "${GITHUB_REF#refs/tags/}" --force
                    git push origin "${GITHUB_REF#refs/tags/}" --force
