name: Downgraded Release

on:
    push:
        tags:
            - '*'

jobs:
    downgrade_release:
        runs-on: ubuntu-latest

        steps:
            -   uses: "actions/checkout@v3"
                with:
                    token: ${{ secrets.WORKFLOWS_TOKEN }}

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.1
                    coverage: none

            # but no dev packages
            -   run: composer update --no-dev --ansi

            # get rector to "rector-local" directory, to avoid downgrading itself in the /vendor
            -   run: mkdir rector-local
            -   run: composer require rector/rector --working-dir rector-local --ansi

            # downgrade /src and /vendor to PHP 8.0
            -   run: rector-local/vendor/bin/rector process src vendor --config build/rector-downgrade-php-80.php --ansi

            # copy PHP 7.2 composer
            -   run: cp build/composer-php-80.json composer.json

            # clear the dev files
            -   run: rm -rf build .github tests schema

            # setup git user
            -
                run: |
                    git config user.email "action@github.com"
                    git config user.name "GitHub Action"

            # publish to the same repository with a new tag
            -
                name: "Tag Downgraded Code"
                run: |
                    # separate a "git add" to add untracked (new) files too
                    git add --all
                    git commit -m "release PHP 8.0 downgraded"

                    # force push tag, so there is only 1 version
                    git tag "${GITHUB_REF#refs/tags/}" --force
                    git push origin "${GITHUB_REF#refs/tags/}" --force
