name: Install Along PHP 8.0

on:
    push:

jobs:
    install_along_php_80:
        runs-on: ubuntu-latest

        steps:
            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.0
                    coverage: none

            -   run: composer require tomasvotruba/phpunit-10-for-php-8 --dev

            -   run: vendor/bin/phpunit
