name: PHP 8.0 Linter

on:
    push:

jobs:
    php_linter:
        runs-on: ubuntu-latest

        steps:
            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.0
                    coverage: none

            -   run: composer require tomasvotruba/phpunit-10-for-php-8 --dev

            -   run: vendor/bin/parallel-lint tomasvotruba/phpunit-10-for-php-8
